"""add_final_tables_v4

Revision ID: 48052edef7f9
Revises: 889bae6387a2
Create Date: 2026-01-04 18:18:10.416738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48052edef7f9'
down_revision: Union[str, None] = '889bae6387a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_alerts_id'), 'community_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_community_alerts_title'), 'community_alerts', ['title'], unique=False)
    op.create_table('family_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('primary_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('can_book_on_behalf', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['primary_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('service_type', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('next_run_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_subscriptions_id'), 'maintenance_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_subscriptions_service_type'), 'maintenance_subscriptions', ['service_type'], unique=False)
    op.create_table('mesh_teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('leader_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesh_teams_id'), 'mesh_teams', ['id'], unique=False)
    op.create_index(op.f('ix_mesh_teams_name'), 'mesh_teams', ['name'], unique=False)
    op.create_table('mesh_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['mesh_teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesh_members_id'), 'mesh_members', ['id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('contract_terms', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_index(op.f('ix_mesh_members_id'), table_name='mesh_members')
    op.drop_table('mesh_members')
    op.drop_index(op.f('ix_mesh_teams_name'), table_name='mesh_teams')
    op.drop_index(op.f('ix_mesh_teams_id'), table_name='mesh_teams')
    op.drop_table('mesh_teams')
    op.drop_index(op.f('ix_maintenance_subscriptions_service_type'), table_name='maintenance_subscriptions')
    op.drop_index(op.f('ix_maintenance_subscriptions_id'), table_name='maintenance_subscriptions')
    op.drop_table('maintenance_subscriptions')
    op.drop_table('family_links')
    op.drop_index(op.f('ix_community_alerts_title'), table_name='community_alerts')
    op.drop_index(op.f('ix_community_alerts_id'), table_name='community_alerts')
    op.drop_table('community_alerts')
    # ### end Alembic commands ###
