"""add_jifunze_table

Revision ID: ecb0e7ed343c
Revises: 48052edef7f9
Create Date: 2026-01-04 18:25:21.894274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecb0e7ed343c'
down_revision: Union[str, None] = '48052edef7f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diy_guides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('tools_required', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diy_guides_category'), 'diy_guides', ['category'], unique=False)
    op.create_index(op.f('ix_diy_guides_id'), 'diy_guides', ['id'], unique=False)
    op.create_index(op.f('ix_diy_guides_title'), 'diy_guides', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diy_guides_title'), table_name='diy_guides')
    op.drop_index(op.f('ix_diy_guides_id'), table_name='diy_guides')
    op.drop_index(op.f('ix_diy_guides_category'), table_name='diy_guides')
    op.drop_table('diy_guides')
    # ### end Alembic commands ###
